image: node:alpine

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - docker build -t lab.buckless.com/core/client .
    - yarn lint

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" lab.buckless.com
    - docker push lab.buckless.com/core/client

