image: lab.buckless.com:4567/core/docker-node-alpine

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build
  - push

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - yarn build:docker
    - docker run -it lab.buckless.com:4567/core/client yarn lint

push:
  stage: push
  only:
    - master
  script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" lab.buckless.com:4567
    - docker push lab.buckless.com:4567/core/client
