image: node:alpine

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - apk add --no-cache git openssh make gcc g++ python
  - yarn

test:
  stage: test
  script:
    - yarn build
    - yarn lint

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker build -t lab.buckless.com/core/manager .
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" lab.buckless.com
    - docker push lab.buckless.com/core/manager

