language: node_js
sudo: false

services:
  - docker

node_js:
  - 8

script:
  - yarn test
  - yarn lint

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t buckless/image-server .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push buckless/image-server;
    fi
