language: node_js
sudo: false

env:
  - CXX=g++-4.8

node_js:
  - '7'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libpcsclite1
      - libpcsclite-dev
      - pcscd

install:
  - yarn install

script:
  - yarn run build
  - yarn run lint
