language: node_js
sudo: required
node_js:
  - '5'
  - '4.1'
  - '4.0'
  - '0.12'

matrix:
  allow_failures:
    - node_js: '4.1'
    - node_js: '4.0'
    - node_js: '0.12'

before_install:
  - "source /etc/lsb-release"
  - "echo \"deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main\" | sudo tee /etc/apt/sources.list.d/rethinkdb.list"
  - "wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -"
  - "sudo apt-get update -y"

install:
  - "sudo apt-get install rethinkdb -y"
  - "npm install -g mocha gulp"
  - "npm install"
  - "rethinkdb&"

script:
  - "npm run test:coverage"

after_script:
  - "npm run coveralls"

compiler: clang-3.6
env:
  - CXX=clang-3.6
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8
