language: node_js
sudo: false
node_js:
  - '7'
  - '6'

addons:
  rethinkdb: '2'

install:
  - "npm install -g mocha gulp"
  - "npm install"
  - "rethinkdb&"

script:
  - "npm run test:coverage"
  - "npm run lint"

after_script:
  - "npm run coveralls"
