version: '3'
services:
    reverse_proxy:
        container_name: buckless_reverse_proxy
        build: ./images/reverse_proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./volumes/reverse_proxy/server.conf:/etc/nginx/conf.d/server.conf

    sql:
        container_name: buckless_sql
        image: postgres:alpine
        expose:
            - "5432"
        environment:
            - POSTGRES_DB=buckless
            - POSTGRES_USER=buckless
            - POSTGRES_PASSWORD=buckless
        volumes:
            - ./volumes/database/data:/var/lib/postgresql/data

    cache:
        container_name: buckless_cache
        image: 'redis:alpine'
        volumes:
            - './volumes/cache/data:/data'
            - ./volumes/cache/redis.conf:/usr/local/etc/redis/redis.conf
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

    adminer:
        container_name: buckless_adminer
        image: adminer
        restart: always
        expose:
            - "8080"
        ports:
            - "8080:8080"
